---
booktitle: 'Proceedings of the KDD 2017: Workshop on Anomaly Detection in Finance'
shortname: KDDADF
sections:
- name: Preface
  title: Preface
- name: Invited Papers
  title: Invited Papers
- name: Contributed Papers
  title: Contributed Papers
volume: 71
year: '2017'
start: 2017-08-14
end: 2017-08-14
url: http://proceedings.mlr.press
author:
  name: PMLR
location: Halifax, Nova Scotia, Canada
published: 2018-01-07
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 2640-3498
id: KDDADF-2017
month: 0
cycles: false
editor:
- given: Archana
  family: Anandakrishnan
- given: Senthil
  family: Kumar
- given: Alexander
  family: Statnikov
- given: Tanveer
  family: Faruquie
- given: Di
  family: Xu
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the KDD 2017: Workshop on Anomaly Detection in Finance on 14 August 2017

  Published as Volume 71 by the Proceedings of Machine Learning Research on 07 January 2018.

  Volume Edited by:
    Archana Anandakrishnan

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 14 Aug
baseurl: "/v71"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
plugins:
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v71
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: KDD 2017 Workshop on Anomaly Detection in Finance
  url: 
  location: 
  dates:
  - 2017-08-14
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
